# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’

target 'Brightcove-Sample-Swift’ do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'Brightcove-Player-SDK'
  # Pods for Brightcove-Sample-Swift

end
