# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DACAdsSDK-FBAudienceNetwork-Sample-ObjectiveC' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'FBAudienceNetwork'

  # Pods for DACAdsSDK-FBAudienceNetwork-Sample-ObjectiveC

end
